# Generated by Django 5.1.5 on 2025-02-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imagem", models.URLField(verbose_name="Imagem do Produto")),
                (
                    "nome",
                    models.CharField(max_length=255, verbose_name="Nome do Produto"),
                ),
                (
                    "preco",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Preço do Produto"
                    ),
                ),
                (
                    "parcelamento",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Opção de Parcelamento",
                    ),
                ),
                ("link", models.URLField(verbose_name="Link do Produto")),
                (
                    "preco_sem_desconto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Preço sem Desconto",
                    ),
                ),
                (
                    "percentual_desconto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        verbose_name="Percentual de Desconto",
                    ),
                ),
                (
                    "tipo_entrega",
                    models.CharField(
                        choices=[("Full", "Full"), ("Normal", "Normal")],
                        max_length=50,
                        verbose_name="Tipo de Entrega",
                    ),
                ),
                (
                    "frete_gratis",
                    models.BooleanField(default=False, verbose_name="Frete Grátis"),
                ),
            ],
        ),
    ]
