# Generated by Django 5.1.5 on 2025-02-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="parcelamento",
            field=models.CharField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Opção de Parcelamento",
            ),
        ),
    ]
