# Generated by Django 5.1.5 on 2025-02-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0002_alter_produto_parcelamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="link",
            field=models.CharField(max_length=500),
        ),
    ]
