# Generated by Django 5.1.5 on 2025-02-05 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogo", "0003_alter_produto_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produto",
            name="link",
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name="produto",
            name="nome",
            field=models.CharField(max_length=500, verbose_name="Nome do Produto"),
        ),
        migrations.AlterField(
            model_name="produto",
            name="parcelamento",
            field=models.CharField(
                blank=True,
                max_length=1000,
                null=True,
                verbose_name="Opção de Parcelamento",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="percentual_desconto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="Percentual de Desconto",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco",
            field=models.DecimalField(
                decimal_places=2, max_digits=12, verbose_name="Preço do Produto"
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="preco_sem_desconto",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                verbose_name="Preço sem Desconto",
            ),
        ),
        migrations.AlterField(
            model_name="produto",
            name="tipo_entrega",
            field=models.CharField(
                choices=[("Full", "Full"), ("Normal", "Normal")],
                max_length=100,
                verbose_name="Tipo de Entrega",
            ),
        ),
    ]
